---
galaxy_info:
  role_name: website_setup
  author: Eric Ames (ericcames)
  description: Creates the website we need to support Mark Lowcher's f5 demos
  license: MIT License
  min_ansible_version: "2.16"
