---
galaxy_info:
  role_name: vm
  author: Eric Ames (ericcames)
  description: Creates and removes the VMs we need to support Mark Lowcher's f5 demos
  license: MIT License
  min_ansible_version: "2.16"
